### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by amgart** [TheMich4/iracing-api#5]
Hi, and thanks for this library!
I just discovered it today and it is really useful.

When executing the /auth call with email and password,  the call returns  'Invalid username or password'. 
This is working on 0.1.11.

EDIT:
I have checked the call in the Development Tools and it seems that the password parameter is encoded in a different way between both versions. Hope this helps

Thanks!!

Albert

**Comment by zzm634** [comment]
looking at the code, the call to "encryptPassword" has the parameters swapped.

**Comment by TheMich4** [comment]
Thanks for mentioning this issue. Login issues should be fixed in 0.1.13 that was just published!

**Comment by amgart** [comment]
Hello! 
I can confirm that it works perfectly on 0.1.13. Thanks for fixing it quickly! :)
