### ISSUE TITLE
Remove dependency on deasync

### ISSUE THREAD

**Issue by zzm634** [TheMich4/iracing-api#7]
`deasync` is hack. It's a bad package and a bad idea. And it causes build problems when used on different machines and under different circumstances because it is a hack.

I know that `tough-cookie` seems to rely on it, but if `tough-cookie` needs `deasync` to work at runtime, then it too is a bad package and should be avoided.

**Comment by TheMich4** [comment]
Hi @zzm634, I'm aware of this and that's why I'm looking into solutions right now. My goal is to have it available in next version.

**Comment by zzm634** [comment]
Awesome, great work!
