### ISSUE TITLE
Return metadata in getLeagueDirectory

### ISSUE THREAD

**Issue by zzm634** [TheMich4/iracing-api#9]
In a previous revision (like 0.1.11 or something around there) `getLeagueDirectory` would return the raw result from the iRacing API, which included some metadata like the total count, offset, and size of results. I was making use of this extra to show progress and pagination stuff to the user. The new API just returns `League[]`, which seems more useful at first, but throws away the pagination metadata.

For this endpoint, and presumably others that work on pages, it would be better to return an object with the metadata intact

**Comment by TheMich4** [comment]
My reasoning was that it would be better to get final data from method itself. But i see you reasoning that you might want to get original response.

My suggested solution would be creating an extra argument for those methods that will allow you to define if you want to get an original response or parsed data.

**Comment by zzm634** [comment]
It's data that's already present in the response; it's not like you can tell the iRacing server not to send it, so it wouldn't make the call any more efficient.

It's also not a big deal to deference the results from a nested property when you're actually using the library.

`for (const league of (await ir.getLeagueDirectory()).leagues) {` 
vs 
`for (const league of await ir.getLeagueDirectory()) {`

I can hardly tell the difference
